### ISSUE TITLE
Getting "fatal: Not a git repository" error

### ISSUE THREAD

**Issue by ChrisMBarr** [therealklanni/guppy-cli#3]
I have installed `git-guppy` and `gupply-cli`into my project, but uppon attempting to install a guppy hook package, I was getting errors.  It seemed odd to me, so I took a step back and saw that all of these packages had a dependency on this one.

So, running the simple `guppy` command give me this following:

```
C:\path\to\my\project>guppy
fatal: Not a git repository (or any of the parent directories): .git
```

This totally is a git repository, so I'm not sure what the issue here is.  Perhaps it just can't write to this directory?
![image](https://cloud.githubusercontent.com/assets/463685/11121995/ff67359a-8926-11e5-8d93-36be10d6a202.png)

**Comment by therealklanni** [comment]
@chrismbarr is it a submodule? See #2 for reference

**Comment by ChrisMBarr** [comment]
It's not a submodule.  The path I am accessing in the command line is the same as the folder that is shown.  the `/.git/` is a directory.  I looked in your node package and manually moved a `pre-commit` file into `/.git/hooks/` that properly called my gulp task, so that works when I do it manually, but it doesn't seem to properly install.

I'm probably not going to continue to look into this since we now have our source control server running gulp tasks and reporting validation errors to everyone in our Slack channel, which i think might work better for our team anyway.

**Comment by therealklanni** [comment]
It may just be a Windows issue. Since I don't have Windows to test this on, and you're not going to look into it anymore, I'm going to close this. Feel free to reopen if needed.
